name = "StaticArraysBlasInterface"
uuid = "3c95a420-e72f-46bd-bd8e-135251b8d06f"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
